## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'flim'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_flim' #to modify
description = 'Set of PyMoDAQ plugins for FLIM Measurements (Fluorescence Lifetime Imaging Microscopy) (using a conjugation of Time-Correlated Single Photon Counting (TSCPC) and xy stages)'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['serial',
                     'scikit-image',]
##